config/routes.rb
Rails.application.routes.draw do
  resources :loans

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  enum property_type: ['single_family', 'duplex', 'triplex', '4-plex', 'condo']

  def total_income
    (base_income + rental_income + commission).to_f.round(2)
  end

  def housing_expense_ratio
    ((mortgage_payment + mortgage_insurance + homeowner_insurance + property_tax + hoa_due) / total_income).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    @check_loan_object = CheckLoanService.new(@loan)

    respond_to do |format|
      if @check_loan_object.is_valid?
        format.html { redirect_to @loan, notice: I18n.t("success") }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @check_loan_object.error_message, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:address, :property_type, :mortgage_payment, :mortgage_insurance, :homeowner_insurance, :property_tax, :hoa_due, :first_name, :last_name, :email, :credit_score, :base_income, :rental_income, :commission)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>McTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @check_loan_object && @check_loan_object.error_message %>
    <div id="error_explanation">
      <%= @check_loan_object.error_message%>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br>
    <%= f.select :property_type, options_for_select(Loan.property_types.keys) %>
  </div>
  <div class="field">
    <%= f.label :mortgage_payment %><br>
    <%= f.text_field :mortgage_payment %>
  </div>
  <div class="field">
    <%= f.label :mortgage_insurance %><br>
    <%= f.text_field :mortgage_insurance %>
  </div>
  <div class="field">
    <%= f.label :homeowner_insurance %><br>
    <%= f.text_field :homeowner_insurance %>
  </div>
  <div class="field">
    <%= f.label :property_tax %><br>
    <%= f.text_field :property_tax %>
  </div>
  <div class="field">
    <%= f.label :hoa_due %><br>
    <%= f.text_field :hoa_due %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :credit_score %><br>
    <%= f.number_field :credit_score %>
  </div>
  <div class="field">
    <%= f.label :base_income %><br>
    <%= f.text_field :base_income %>
  </div>
  <div class="field">
    <%= f.label :rental_income %><br>
    <%= f.text_field :rental_income %>
  </div>
  <div class="field">
    <%= f.label :commission %><br>
    <%= f.text_field :commission %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Loans</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Property type</th>
      <th>Mortgage payment</th>
      <th>Mortgage insurance</th>
      <th>Homeowner insurance</th>
      <th>Property tax</th>
      <th>Hoa due</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Credit score</th>
      <th>Base income</th>
      <th>Rental income</th>
      <th>Commission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.address %></td>
        <td><%= loan.property_type %></td>
        <td><%= loan.mortgage_payment %></td>
        <td><%= loan.mortgage_insurance %></td>
        <td><%= loan.homeowner_insurance %></td>
        <td><%= loan.property_tax %></td>
        <td><%= loan.hoa_due %></td>
        <td><%= loan.first_name %></td>
        <td><%= loan.last_name %></td>
        <td><%= loan.email %></td>
        <td><%= loan.credit_score %></td>
        <td><%= loan.base_income %></td>
        <td><%= loan.rental_income %></td>
        <td><%= loan.commission %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @loan.address %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @loan.property_type %>
</p>

<p>
  <strong>Mortgage payment:</strong>
  <%= @loan.mortgage_payment %>
</p>

<p>
  <strong>Mortgage insurance:</strong>
  <%= @loan.mortgage_insurance %>
</p>

<p>
  <strong>Homeowner insurance:</strong>
  <%= @loan.homeowner_insurance %>
</p>

<p>
  <strong>Property tax:</strong>
  <%= @loan.property_tax %>
</p>

<p>
  <strong>Hoa due:</strong>
  <%= @loan.hoa_due %>
</p>

<p>
  <strong>First name:</strong>
  <%= @loan.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @loan.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @loan.email %>
</p>

<p>
  <strong>Credit score:</strong>
  <%= @loan.credit_score %>
</p>

<p>
  <strong>Base income:</strong>
  <%= @loan.base_income %>
</p>

<p>
  <strong>Rental income:</strong>
  <%= @loan.rental_income %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @loan.commission %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>